### ISSUE TITLE
Be able to exclude some pages

### ISSUE THREAD

**Issue by xplosionmind** [keithmifsud/jekyll-target-blank#55]
It would be great if in `_config.yml` the user could add:

```yaml
target-blank:
  exclude:
    - "/index.html"
    - "/somepage"
    -  "/some-other-page"
```

So that the pages written can be excluded by the plugin.

Thank you very much!

Best,   
T
